### ISSUE TITLE
Fails on IE11

### ISSUE THREAD

**Issue by rfreitas** [xdumaine/enumerateDevices#5]
The `Promise` api is not supported on IE11.

**Comment by xdumaine** [comment]
IE 11 doesn't have WebRTC device access, so I'd recommend not executing this code in IE 11.

**Comment by rfreitas** [comment]
Well, this code is already handling browsers that don't support WebRTC, such as Safari, Safari iOS and some android browsers. It doesn't support IE11 not because it lacks WebRTC, but solely because it lacks promises.
I think the non promise based api could easily support IE11.
